export const SAVE_CURRENT_WEATHER_SUCCESS = "SAVE_CURRENT_WEATHER_SUCCESS";
export const SAVE_CITY = "SAVE_CITY";
export const SAVE_MODAL_DETAILS = "SAVE_MODAL_DETAILS";
export const SET_MODAL = "SET_MODAL";
